[package]
name = "skejj-engine"
version = "0.1.0"
edition = "2021"

[lib]
crate-type = ["lib"]

[dependencies]
serde = { version = "1", features = ["derive"] }
petgraph = "0.8"
thiserror = "2"
chrono = "0.4"
