[package]
name = "skejj-node"
version = "0.1.0"
edition = "2021"

[lib]
crate-type = ["cdylib"]

[dependencies]
napi = { version = "3", default-features = false, features = ["napi4"] }
napi-derive = "3"
skejj-engine = { path = "../engine" }

[build-dependencies]
napi-build = "2"
